### ISSUE TITLE
Python package dependencies are not clear

### ISSUE THREAD

**Issue by mertyildiran** [reith/deepspeech-playground#2]
I couldn't be able to test the pre-trained model because Python package dependencies are unclear.

I tried to run `python3 test.py` but I got this error:

```
Using TensorFlow backend.
Traceback (most recent call last):
  File "test.py", line 10, in <module>
    from model import compile_test_fn
  File "/home/mertyildiran/Downloads/deepspeech-playground/model.py", line 6, in <module>
    import ctc
ImportError: No module named 'ctc'
```

What is `ctc` library? How can I install it? There is no library named `ctc` in PyPI. As a suggestion, it's better to have a `requirements.txt` file.

I tried to run `python3 visualize.py` but I got:

```
Using TensorFlow backend.
usage: visualize.py [-h] [--test_file TEST_FILE] [--load_dir LOAD_DIR]
                    [--weights_file WEIGHTS_FILE] [--interactive]
                    train_desc_file
visualize.py: error: the following arguments are required: train_desc_file
```

Which one of the files is `train_desc_file` file? Could you improve README.md by adding a step-by-step guide for testing pre-trained models. :blush: Thank so much, great work :+1:

**Comment by reith** [comment]
Sorry, I never used `test.py` before and It remained from Baidu's repo. Here `ctc` module is [sherjilozair's binding around warp-ctc](https://github.com/sherjilozair/ctc) but you won't need it since It'll use Theano 0.10 bindings or Tensorflow's.

Now I changed `test.py` to use new codes. You can run it like:
```
python test.py descs/test-clean.json pre-trained/model_45_config.json models/44-cont-45-i14490-dur20-lr5e-5/best-val-weights.h5
```
It just mimics Baidu's script so you get just loss which is not that meaningful. I'll add more reports when I fixed WER calculation, right now It calculates CER.

The only module this repo needs that Baidu repo does not, is edit_distance.

**Comment by reith** [comment]
See [here](https://github.com/baidu-research/ba-dls-deepspeech#data) for train_desc_file
